TourismManagementSystem/Controllers/AdminDashboardController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TourismManagementSystem.Models;

namespace TourismManagementSystem.Controllers
{
    public class AdminDashboardController : Controller
    {
        //Intialization object of DBcontext class
        TourismDbContext db = new TourismDbContext();

        // GET: AdminDashboard
        public ActionResult Index()
        {
            //This is used for more security if someonw trying go directly to AdminDashboard/index page
            if (Session["AdminUserId"] == null)
            {
                return RedirectToAction("Index", "AdminLogin");
            }
            else
            {
                return View();
            }
        }

        //Creating method for logout

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "AdminLogin");

        }

        //adding new Admin our Admin table
        public ActionResult AddAdmin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(Admin admin)
        {
            if (ModelState.IsValid == true) //if all data entered is valide
            {
                db.Admins.Add(admin);
                try { 
                    int a = db.SaveChanges(); //To save changes in database
                    if (a > 0)
                    {
                        TempData["SuccessMessage"] = "Admin added successfully!";
                        ModelState.Clear(); // to clear entered data from html page
                    }
                    else
                    {
                        TempData["SuccessMessage"] = "Opration failed, Please try again!";
                        
                    }
                }
                catch(DbEntityValidationException e)
                {
                    TempData["SuccessMessage"] = "Opration failed, Please try again!";
                }
                
                

            }
                return View();
        }

        //To get the list of all Admin details
        [HttpGet]
        public ActionResult GetAdmin()
        {
            var fetch = db.Admins.ToList();
            return View(fetch);
        }

        //To Edit the admin details
        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            var obj = db.Admins.Find(id);
            return View(obj);
        }
        [HttpPost]
        public ActionResult EditAdmin(Admin adm)
        {
            
            try
            {
                db.Entry(adm).State = System.Data.Entity.EntityState.Modified; //used to modifi the admin
                db.SaveChanges();
                TempData["SuccessMessage"] = "Changes saved!";

            } 
            catch (DbEntityValidationException e)
            {
                TempData["SuccessMessage"] = "Operation Failed try again!";
            }
            
            return View();
        }

        
        //To delete admin
        [HttpGet]
        public ActionResult DeleteAdmin( int id)
        {
            var obj = db.Admins.Find(id); //To Get details of Admin as per ID
            return View(obj);
        }

        //To delete admin after confirmation
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAdminConfirmed(int id)
        {
            var adm = db.Admins.Find(id);

            if (adm == null)
            {
                return HttpNotFound();
            }

            db.Admins.Remove(adm); //to remove admin from admin table
            db.SaveChanges();
            TempData["SuccessMessage"] = "Admin deleted successfully!";
            return RedirectToAction("GetAdmin", TempData["SuccessMessage"]);
        }

        [HttpGet]
        public ActionResult GetBooking(string searchStr, int page = 1)
        {
            //This part is used for layout purpose
            if (Session["AdminUserId"] != null)
            {
                ViewBag.Role = "Admin";
            }
            else
            {
                ViewBag.Role = "Employee";
            }

            var fetch = db.payments.ToList();
            if (!string.IsNullOrEmpty(searchStr))
            {
                fetch = db.payments.Where(p => (p.CustomerName.Contains(searchStr) || p.PackageName.Contains(searchStr))).ToList();
            }
            if (fetch == null)
            {
                fetch = new List<Payment>(); // Create an empty list if fetch is null
            }
            //To order data in decending order by start date
            fetch = fetch.OrderByDescending(item => item.StartDate).ToList();

            int pageSize = 5; // Specify the page size
            int totalCount = fetch.Count();
            int totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);

            ViewBag.pageNumber =page;
            ViewBag.TotalPages = totalPages;
            ViewBag.SearchStr = searchStr;

            // Perform pagination
            var paginatedData = fetch.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Pass the paginated data to the view
            return View(paginatedData);
        }



        /*
        //To get all booking details 
        [HttpGet]
        public ActionResult GetBooking()
        {
            //This part is used for layout purpose
            if (Session["AdminUserId"] != null)
            {
                ViewBag.Role = "Admin";
            }
            else
            {
                ViewBag.Role = "Employee";
            }
            var fetch = db.payments.ToList();
            if (fetch == null)
            {
                fetch = new List<Payment>(); // Create an empty list if fetch is null
            }

            return View(fetch);
        }

        */
        //for Canceling booking of customer
        public ActionResult CancelBooking(int id)
        {
            if (Session["AdminUserId"] != null)
            {
                ViewBag.Role = "Admin";
            }
            else
            {
                ViewBag.Role = "Employee";
            }
            var obj = db.payments.Find(id);
            return View(obj);
        }

        //for booking Cancel confirmation 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CancelBookingConfirmed(int id)
        {
            
            if (Session["AdminUserId"] != null)
            {
                ViewBag.Role = "Admin";
            }
            else
            {
                ViewBag.Role = "Employee";
            }
            var pay = db.payments.Find(id);
            if (pay == null)
            {
                
                return HttpNotFound();
            }

            db.payments.Remove(pay);
            int a = db.SaveChanges();
            if (a > 0)
            {

                TempData["SuccessMessage"] = $"Booking Canceled for Ticket No.: {pay.TicketNumber} !";

            }
            else
            {
                TempData["SuccessMessage"] = "Operation failed!";
            }
            return RedirectToAction("GetBooking", TempData["SuccessMessage"]);
        }
    }
}

TourismManagementSystem/Controllers/LoginSingupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Optimization;
using TourismManagementSystem.Models;

namespace TourismManagementSystem.Controllers
{
    public class LoginSingupController : Controller
    {
        //Creating the object of Dbcontext class : TourismDbContext
        TourismDbContext db = new TourismDbContext();

        // GET: LoginSingup
        public ActionResult Index()
        {
            Customer cust = new Customer();
            return View(cust);
        }

        //creating post method for Login
        [HttpPost]
        public ActionResult Index(Customer customer)
        {
            //creating variable for user 
            var user = db.Customers.Where(model => model.CustomerName == customer.CustomerName && model.CustomerPassword == customer.CustomerPassword).FirstOrDefault();
            if(user != null)
            {
                // Session["UserId"] = customer.CustomerId.ToString(); // to record the login sessions
                Session.Add("UserId", user.CustomerId);
                Session.Add("UserName", user.CustomerName);
             
                TempData["LoginSuccessMessage"] = "<script>alert('Login successfull') </script>"; // To show that login is successfull
                
                return RedirectToAction("Index", "User");  // after login it will redirect to user dashboard
            
            }

            else  // if login failed it will redirect to same login page with error msg
            {
                ViewBag.ErrorMessage = "Login Failed !! \n Please enter correct user name or password";
                return View();
            }
            
        }
        public ActionResult SingUp()
        {
            return View();
        }

        //creating post method for signup
        [HttpPost]
        public ActionResult SingUp(Customer customer)
        {
            if(ModelState.IsValid==true) //if all data entered is valide
            {
                db.Customers.Add(customer);
                int a = db.SaveChanges(); // If changes saved then will return >0 else 0
                if(a >0)
                {
                    ViewBag.InsertMessage = "<script>alert('Registration successfully') </script>";
                    ModelState.Clear(); // to clear entered data from html page
                }
                else
                {
                    ViewBag.InsertMessage = "<script>alert('Registration Failed') </script>";
                }

            }
            return View();
        }
    }
}

TourismManagementSystem/Views/Shared/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_LayoutMainPage.cshtml";
}

<h2>Success</h2>

TourismManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - </title>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary">
        <div class="container">

            <div class="d-flex justify-content-start">
                @Html.ActionLink("Ocean Tourism", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>

            <div class="collapse navbar-collapse d-sm-inline-flex ">
                <ul class="navbar-nav flex-grow-1 justify-content-end">
                    <li style="padding-right:35px">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li style="padding-right:35px">@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li style="padding-right:35px">@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Login
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1> Welcome to Ocean Tourism login Page
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>

                        <div class="modal-body">
                            <div class="modal-body d-flex justify-content-between">
                                <button type="button" class="btn btn-primary">
                                    @Html.ActionLink("Customer Login", "Index", "LoginSingup", new { area = "" }, new { @class = "nav-link" })
                                </button>

                                <button type="button" class="btn btn-primary">
                                    @Html.ActionLink("Admin Login", "Index", "AdminLogin", new { area = "" }, new { @class = "nav-link" })
                                </button>

                                <button type="button" class="btn btn-primary">
                                    @Html.ActionLink("Employee Login", "Index", "EmployeeLogin", new { area = "" }, new { @class = "nav-link" })
                                </button>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    @RenderBody()

    <hr />
    <footer class="sticky-footer ">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; Ocean Tourism 2023</span>
            </div>
        </div>
    </footer>
    <script>
        $(document).ready(function () {
            $("#loginLink").click(function (e) {
                e.preventDefault(); // Prevent the default link behavior

                // Trigger the modal manually
                $("#loginModal").modal("show");
            });
        });
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/5.0.0/js/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TourismManagementSystem/Views/Shared/_Layout_List_AdminDashboard.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    <link href="~/Assests/AdminDashboard/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Assests/AdminDashboard/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body>
    <div>
        <nav class="navbar navbar-expand navbar-light  topbar mb-4 static-top shadow" style="background-color: #B0C4DE; ">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <div class="d-flex justify-content-start" style="font-weight:600;">
                @Html.ActionLink("Ocean Tourism", "Index", "AdminDashboard", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
                <li style="padding-right:35px; margin-top:15px;">@Html.ActionLink("Dashboard", "Index", "AdminDashboard", new { area = "" }, new { @class = "nav-link" })</li>

                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                         aria-labelledby="searchDropdown">
                        <form class="form-inline mr-auto w-100 navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small"
                                       placeholder="Search for..." aria-label="Search"
                                       aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="button">
                                        <i class="fas fa-search fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>

                <!-- Nav Item - Alerts -->
                <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-bell fa-fw" style="color:white;"></i>
                        <!-- Counter - Alerts -->
                        <span class="badge badge-danger badge-counter ">3+</span>
                    </a>
                    <!-- Dropdown - Alerts -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="alertsDropdown">
                        <h6 class="dropdown-header">
                            Alerts Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-primary">
                                    <i class="fas fa-file-alt text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 12, 2019</div>
                                <span class="font-weight-bold">A new monthly report is ready to download!</span>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-success">
                                    <i class="fas fa-donate text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 7, 2019</div>
                                $290.29 has been deposited into your account!
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-warning">
                                    <i class="fas fa-exclamation-triangle text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 2, 2019</div>
                                Spending Alert: We've noticed unusually high spending for your account.
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                    </div>
                </li>

                <!-- Nav Item - Messages -->
                <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-envelope fa-fw" style="color:white;"></i>
                        <!-- Counter - Messages -->
                        <span class="badge badge-danger badge-counter">7</span>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="messagesDropdown">
                        <h6 class="dropdown-header">
                            Message Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src="img/undraw_profile_1.svg"
                                     alt="...">
                                <div class="status-indicator bg-success"></div>
                            </div>
                            <div class="font-weight-bold">
                                <div class="text-truncate">
                                    Hi there! I am wondering if you can help me with a
                                    problem I've been having.
                                </div>
                                <div class="small text-gray-500">Emily Fowler · 58m</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src="img/undraw_profile_2.svg"
                                     alt="...">
                                <div class="status-indicator"></div>
                            </div>
                            <div>
                                <div class="text-truncate">
                                    I have the photos that you ordered last month, how
                                    would you like them sent to you?
                                </div>
                                <div class="small text-gray-500">Jae Chun · 1d</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src="img/undraw_profile_3.svg"
                                     alt="...">
                                <div class="status-indicator bg-warning"></div>
                            </div>
                            <div>
                                <div class="text-truncate">
                                    Last month's report looks great, I am very happy with
                                    the progress so far, keep up the good work!
                                </div>
                                <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                                     alt="...">
                                <div class="status-indicator bg-success"></div>
                            </div>
                            <div>
                                <div class="text-truncate">
                                    Am I a good boy? The reason I ask is because someone
                                    told me that people say this to all dogs, even if they aren't good...
                                </div>
                                <div class="small text-gray-500">Chicken the Dog · 2w</div>
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                    </div>
                </li>

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline small" style="color:black; font-size:18px; padding-right:10px"> @Session["AdminUserName"]</span>
                        <img class="img-profile rounded-circle"
                             src="~/Assests/AdminDashboard/img/undraw_profile.svg">
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="userDropdown">
                        

                      
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Logout
                        </a>
                    </div>
                </li>

            </ul>

        </nav><!--End of nav bar-->
        <div class="container">
            @RenderBody()
            @RenderSection("Scripts", required: false)
        </div>
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Ocean Tourism 2021</span>
                </div>
            </div>
        </footer>
        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a> @Html.ActionLink("Logout", "Logout", "AdminDashboard", null, new { @class = "btn btn-primary" })</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/Assests/AdminDashboard/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assests/AdminDashboard/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Assests/AdminDashboard/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Assests/AdminDashboard/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Assests/AdminDashboard/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Assests/AdminDashboard/js/demo/chart-area-demo.js"></script>
    <script src="~/Assests/AdminDashboard/js/demo/chart-pie-demo.js"></script>
</body>
</html>