TourismManagementSystem/Controllers/BankController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TourismManagementSystem.Models;

namespace TourismManagementSystem.Controllers
{
    public class BankController : Controller
    {
        //consuming the BankWebAPI here
      
        public ActionResult VerifyPayment(int id)
        {
            Account acc = new Account(); // Creating a new instance of the Account class
            return View(acc); // Return the View with the Account object as the model
        }

        [HttpPost]
        public ActionResult VerifyPayment(Account acc,int id)
        {
            
            HttpClient client = new HttpClient(); // Create a new instance of HttpClient
            //  base address for the HTTP client
            client.BaseAddress = new Uri("https://localhost:44357/api/");

            // To convert the Account object to JSON string
            string jsonData = JsonConvert.SerializeObject(acc);

            //  HTTP content with JSON data
            var content = new StringContent(jsonData, UnicodeEncoding.UTF8, "application/json"); 


            // Send a POST request to the "BankAPI" endpoint with the JSON content
            Task<HttpResponseMessage> responseTask = client.PostAsync("BankAPI", content);
            responseTask.Wait(); // Waiting for the response


            // To Get the response from the task
            var response = responseTask.Result;

            // Check if the request was successful (status code 2xx)
            if (response.IsSuccessStatusCode)
            {
                // Read the response content as a boolean indicating payment verification result
                bool verificationResult = response.Content.ReadAsAsync<bool>().Result;
                if (verificationResult)
                {
                    // If the details are verified, redirect to the "BuyPackage" action in the "User" controller
                    return RedirectToAction("BuyPackage", "User", new { id = id });
                }
                else
                {
                    // Set an error message in the ViewBag
                    ViewBag.Message = "Payment verification failed.";
                    return View("PaymentError"); // Return the "PaymentError" view
                }
                
            }
            else
            {
                ViewBag.Message = response.Content.ReadAsStringAsync().Result;
                return View("PaymentError");// Return the "PaymentError" view
            }

        }






    }
}

TourismManagementSystem/Views/Bank/PaymentError.cshtml
@{
    ViewBag.Title = "PaymentError";
    Layout = "~/Views/Shared/_LayoutUserDashboard.cshtml";
}


<div class="container-md" style="justify-content:center; width:600px; height:300px; ">
    <img src="~/Assests/Images/Transaction-Failed.png" alt="alternate_text" style="height:200px; width:400px; margin-left:100px;" />
    <h5 style="text-align:center; color:firebrick">Payment Failed Please try again !!</h5>
    <p style="text-align:center;">Please check if the entered card details are correct or not!</p>
    <div class="box" style=" text-align: center; ">
        @Html.ActionLink("Back to main menu", "Index", "User", null, new { @class = "btn btn-secondary" })
    </div>
</div>

TourismManagementSystem/Views/Bank/VerifyPayment.cshtml
@model TourismManagementSystem.Models.Account

@{
    ViewBag.Title = "VerifyPayment";
    Layout = "~/Views/Shared/_LayoutUserDashboard.cshtml";
}

@using (Html.BeginForm("VerifyPayment", "Bank", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
   
    <h4><i class="fa fa-university" style="font-size:35px; color:black; margin-right:10px" aria-hidden="true"></i>Payment Page</h4>
    <p style="color:darkred;">Please enter all details correctly for seamless performance and a successful payment.</p>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    
    <label style="margin-left:12px;"><i class="fa fa-credit-card" aria-hidden="true" style="margin-right:10px;"></i>Card Number</label>
    <div class="col-md-10">
        @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "text-danger" })
        <p style="color:darkred; margin-top:1px;">(Please enter 16 digits Card No.)*</p>
    </div>
</div>

    <div class="form-group">
        <label style="margin-left:12px;">Card Holder Name</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.AccountHolderName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AccountHolderName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CardType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CardType, new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Debit", Value = "Debit" },
                new SelectListItem { Text = "Credit", Value = "Credit" }
            }, "Value", "Text"), "Select Card Type", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CardType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label style="margin-left:12px;">CVV Number</label>
        <div class="col-md-10">
            <input type="password" class="form-control" name="CCVNumber" />
            @Html.ValidationMessageFor(model => model.CCVNumber, "", new { @class = "text-danger" })
            <p style="color:darkred; margin-top:1px;">(Please enter 3 digits Card CVV No.)*</p>
        </div>
    </div>

    <div class="form-group">
        <label style="margin-left:12px;">Card PIN Number</label>
        <div class="col-md-10">
            <input type="password" class="form-control" name="CardPin" />
            @Html.ValidationMessageFor(model => model.CardPin, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Pay Now" class="btn btn-success" />
            @Html.ActionLink("Cancel", "Index", "User", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>
}

<div>
   
</div>